import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashBoardLayout({ children }) {
  return (
    <div className="h-screen flex flex-row">
      {/* left */}
      <div className="w-1/6">l</div>
      {/* right */}
      <div className="w-5/6">r</div>
    </div>
  );
}
